### ISSUE TITLE
"My podcasts" sort by release date incorrect

### ISSUE THREAD

**Issue by purduearrow** [matheus-inacio/grover-podcast#3]
I have purchased Grover Pro and it is a great app! 

Subscribed podcasts under "My Podcasts" are not sorted correctly by release date.  Several podcasts are in the top of the list are many weeks or months old before getting to the most recent ones.  I have deleted all subscribed podcasts and loaded them back into the database via OPML file and initially, all are correct.  As soon as I click any item in the left pane and then click back on "My podcasts", the order of the podcasts is incorrect.

**Comment by matheus-inacio** [comment]
Fixed on version 3.1.6.0
